#!/usr/bin/env python3
"""
Configure script to generate build.ninja with dynamic source file dependencies.

This script scans the project for all source files (.cpp, .h) and CMakeLists.txt
files, then generates build.ninja with these files as implicit dependencies.
This ensures ninja correctly detects when to rebuild after file changes.

Run this script whenever you add or remove source files:
    python3 configure.py

The generated build.ninja should be committed to the repository.
"""

import glob
from pathlib import Path


def find_sources():
    """Find all source files, headers, and CMakeLists.txt files."""
    sources = []
    
    # Find all .cpp and .h files in src, inc, and python directories
    for pattern in ['src/**/*.cpp', 'src/**/*.h', 
                    'inc/**/*.h', 'inc/**/*.hpp',
                    'python/**/*.cpp', 'python/**/*.h']:
        sources.extend(glob.glob(pattern, recursive=True))
    
    # Find all CMakeLists.txt files (excluding extern/)
    for cmake_file in glob.glob('**/CMakeLists.txt', recursive=True):
        if not cmake_file.startswith('extern/') and not cmake_file.startswith('build/'):
            sources.append(cmake_file)
    
    # Sort for consistency
    return sorted(set(sources))


def generate_build_ninja():
    """Generate the build.ninja file with all dependencies."""
    sources = find_sources()
    
    # Format sources for ninja (with line continuations)
    deps_lines = []
    for src in sources:
        deps_lines.append(f"    {src} $")
    # Remove the trailing $ from the last line
    if deps_lines:
        deps_lines[-1] = deps_lines[-1].rstrip(' $')
    
    build_ninja_content = f"""# build.ninja - Ninja build file for phys project
# This file is auto-generated by configure.py - DO NOT EDIT MANUALLY
# Run `python3 configure.py` to regenerate
# Targets are sorted alphabetically

# Simple rule for running shell commands
rule run
  command = $cmd
  description = $desc

# Build the project using CMake
build build: run | $
{chr(10).join(deps_lines)}
  cmd = cmake -S . -B build -GNinja && cmake --build build
  desc = Building project with CMake
  pool = console

# Build container for the specified platform architecture
# Usage: ninja build-container (defaults to x86_64)
#        PLATFORM_ARCH=aarch64 ninja build-container
build build-container: run
  cmd = docker build . -f Containerfile -t phys --build-arg PLATFORM_ARCH=$${{PLATFORM_ARCH:-x86_64}} && docker container rm phys-builder || true && docker create --name phys-builder phys && mkdir -p dist && docker cp phys-builder:/app/wheelhouse/. dist/ && docker container rm phys-builder
  desc = Building container for platform $${{PLATFORM_ARCH:-x86_64}}

# Version bump using commitizen
build bump: run
  cmd = cz bump -s
  desc = Bumping version with commitizen

# Run all CI actions
build ci: run
  cmd = ninja build && ninja format && ninja lint && ninja test
  desc = Running all CI actions
  pool = console

# Clean the build directory
build clean: run
  cmd = cmake --build build --target clean && ruff clean
  desc = Cleaning build directory

# Full clean - remove build directory
build clean-full: run
  cmd = rm -rf build/
  desc = Full clean - removing build directory

# Run formatting tasks
build format: run
  cmd = find src -iname '*.h' -o -iname '*.cpp' | xargs clang-format -i && ruff format src
  desc = Formatting code

# Install the python package
build install: run
  cmd = pip install . --no-deps --force-reinstall -v
  desc = Installing python package
  pool = console

# Run linting tasks
build lint: run
  cmd = run-clang-tidy -p build -header-filter=".*/inc/.*" -exclude-header=".*extern.*" python src tests && ruff check python --exclude "*.pyi"
  desc = Linting code
  pool = console

# Generate python stubs
build stubs: run
  cmd = pybind11-stubgen --output python phys
  desc = Generating python stubs

# Run all tests
build test: run
  cmd = ninja test-cpp && ninja test-python
  desc = Running all tests
  pool = console

# Run C++ core unit tests
build test-cpp: run
  cmd = cd build/tests && ctest --output-on-failure
  desc = Running C++ unit tests
  pool = console

# Run python problem set tests
build test-python: run
  cmd = python -m pytest -v
  desc = Running python tests
  pool = console

# Package as wheel
build wheel: run
  cmd = python -m build --wheel
  desc = Building python wheel
  pool = console

# Default target
default build
"""
    
    with open('build.ninja', 'w') as f:
        f.write(build_ninja_content)
    
    print(f"Generated build.ninja with {len(sources)} source file dependencies")
    print("Dependencies include:")
    print(f"  - {len([s for s in sources if s.endswith('.cpp')])} C++ source files")
    print(f"  - {len([s for s in sources if s.endswith('.h') or s.endswith('.hpp')])} header files")
    print(f"  - {len([s for s in sources if 'CMakeLists.txt' in s])} CMakeLists.txt files")


if __name__ == '__main__':
    generate_build_ninja()
