if(EXISTS "/home/runner/work/physics-1/physics-1/_codeql_build_dir/hello_test[1]_tests.cmake")
  include("/home/runner/work/physics-1/physics-1/_codeql_build_dir/hello_test[1]_tests.cmake")
else()
  add_test(hello_test_NOT_BUILT hello_test_NOT_BUILT)
endif()
