add_test([=[HelloTest.BasicAssertions]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/hello_test [==[--gtest_filter=HelloTest.BasicAssertions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HelloTest.BasicAssertions]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FunctionTest.Add]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/hello_test [==[--gtest_filter=FunctionTest.Add]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FunctionTest.Add]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FunctionTest.Sub]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/hello_test [==[--gtest_filter=FunctionTest.Sub]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FunctionTest.Sub]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FunctionTest.Mul]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/hello_test [==[--gtest_filter=FunctionTest.Mul]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FunctionTest.Mul]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  hello_test_TESTS HelloTest.BasicAssertions FunctionTest.Add FunctionTest.Sub FunctionTest.Mul)
