add_test([=[Vector2Test.Add]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.Add]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.Add]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.AddSelf]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.AddSelf]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.AddSelf]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.Sub]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.Sub]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.Sub]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.SubSelf]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.SubSelf]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.SubSelf]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.Mul]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.Mul]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.Mul]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.MulSelf]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.MulSelf]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.MulSelf]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.Div]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.Div]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.Div]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.DivSelf]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.DivSelf]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.DivSelf]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.DivZero]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.DivZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.DivZero]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.Equal]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.Equal]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.Equal]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.NotEqual]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.NotEqual]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.NotEqual]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.Mag]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.Mag]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.Mag]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.Unit]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.Unit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.Unit]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.Angle]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.Angle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.Angle]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.FromMagAng]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.FromMagAng]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.FromMagAng]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.String]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.String]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.String]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector2Test.Negation]=]  /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests/linalg_test [==[--gtest_filter=Vector2Test.Negation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector2Test.Negation]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/physics-1/physics-1/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  linalg_test_TESTS Vector2Test.Add Vector2Test.AddSelf Vector2Test.Sub Vector2Test.SubSelf Vector2Test.Mul Vector2Test.MulSelf Vector2Test.Div Vector2Test.DivSelf Vector2Test.DivZero Vector2Test.Equal Vector2Test.NotEqual Vector2Test.Mag Vector2Test.Unit Vector2Test.Angle Vector2Test.FromMagAng Vector2Test.String Vector2Test.Negation)
